# Generated by Django 2.2 on 2019-10-05 20:35

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('accounts', '0002_auto_20190926_1520'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
